modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="secure"
version="1.0.0"
displayName="Redacted | By SteveOS Modding"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Maniac_Official"

[[dependencies.secure]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



